FROM python:3.6.5-alpine

#Set working directory
WORKDIR /usr/src/app

#Copy and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install -r requirements.txt

COPY . /usr/src/app

CMD python manage.py run -h 0.0.0.0

